preferences:
  autowire-on-sync-mode: UPDATE_OPTIONAL_DEPENDENCIES
  repositories-mode: FAIL_ON_PROJECT_REPOS

repositories:
  gradle-plugin-portal:
    scope: PLUGINS
  google:
  maven-central:

plugins:
  org.jetbrains.kotlin.jvm:
    alias: kotlin-jvm
    version: 2.1.10
  org.jetbrains.kotlin.android:
    alias: kotlin-android
    version-ref: kotlin-jvm
  org.jetbrains.compose:
    alias: jetbrains-compose
    version: 1.7.3
  org.jetbrains.kotlin.plugin.compose:
    alias: compose-compiler
    version-ref: kotlin-jvm
  com.android.application:
    alias: android-application
    version: 8.9.0
  com.vanniktech.maven.publish:
    alias: maven-publish
    version: 0.31.0

libraries:
  androidx.compose:
    compose-bom:
      version: 2025.03.00
  androidx.compose.foundation:
    foundation:
      version: <no-spec>
  androidx.compose.ui:
    ui:
      version: <no-spec>
  androidx.compose.material3:
    material3:
      version: <no-spec>
  androidx.activity:
    activity-compose:
      version: 1.10.1
  androidx.core:
    core-ktx:
      version: 1.15.0
  androidx.appcompat:
    appcompat:
      version: 1.7.0
  com.google.android.material:
    material:
      version: 1.12.0
  androidx.test.ext:
    junit:
      version: 1.2.1
  androidx.test.espresso:
    espresso-core:
      version: 3.6.1
  junit:
    junit:
      version: 4.13.2